version: '3.3'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 217820324845.dkr.ecr.us-east-2.amazonaws.com/miscsite:latest
    networks:
      - network
    volumes:
      - app_data:/var/www/html/storage/app/public
  db:
    image: 217820324845.dkr.ecr.us-east-2.amazonaws.com/mysql:latest
    restart: always
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_USER: miscite
      MYSQL_PASSWORD: miscite
      MYSQL_DATABASE: miscite
    ports:
      - "3306:3306"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: 217820324845.dkr.ecr.us-east-2.amazonaws.com/nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - app_data:/var/www/html/public/storage
    ports:
      - "80:80"
    networks:
      - network
    links:
      - app

volumes:
  app_data:
    driver: local