version: '3.3'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    volumes:
      - app_data:/var/www/html/storage/app/public

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    volumes:
        - ./deploy/nginx/etc/ssl:/etc/nginx/ssl
        - app_data:/var/www/html/public/storage
    ports:
        - "80:80"
        - "443:443"
    environment:
        - TZ=America/Chicago
        - LETSENCRYPT=true
        - LE_EMAIL=qouiqaismail@gmail.com
        - LE_FQDN=isqoweb.com
        #- SSL_CERT=le-crt.pem
        #- SSL_KEY=le-key.pem
        #- SSL_CHAIN_CERT=le-chain-crt.pem
    networks:
      - network
    links:
        - app

volumes:
  app_data:
    driver: local